### ISSUE TITLE
Bump minimum Python version

### ISSUE THREAD

**Issue by DavidBakerEffendi** [Skippy404/C45DiscordBot#34]
If we [bump to Python 3.7](https://docs.python.org/3/whatsnew/3.7.html) we get:

* dataclasses (basically structs)
* improved `asyncio`

If we [bump to Python 3.8](https://docs.python.org/3/whatsnew/3.8.html) we get:

* walrus operator (new syntax :=)
* Positional-only parameters
* Improved `pickle`

**Comment by DavidBakerEffendi** [comment]
Is this necessary? It will just change our CI/CD and what is required by our servers. We can close this if you guys don't need this.

**Comment by deavmi** [comment]
Improved pickle :eyes:

On 04 April 2020 22:25:29 SAST, David Baker Effendi <notifications@github.com> wrote:
>If we [bump to Python 3.7](https://docs.python.org/3/whatsnew/3.7.html)
>we get:
>
>* dataclasses (basically structs)
>* improved `asyncio`
>
>If we [bump to Python 3.8](https://docs.python.org/3/whatsnew/3.8.html)
>we get:
>
>* walrus operator (new syntax :=)
>* Positional-only parameters
>* Improved `pickle`
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Skippy404/C45DiscordBot/issues/34

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deavmi** [comment]
I don't really, so far, see a need for it. So perhaps close.

On 04 April 2020 22:26:05 SAST, David Baker Effendi <notifications@github.com> wrote:
>Is this necessary? It will just change our CI/CD and what is required
>by our servers. We can close this if you guys don't need this.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Skippy404/C45DiscordBot/issues/34#issuecomment-609084551

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
